name: React CI

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2

      - name: Install dependencies
        working-directory: ./myPage
        run: yarn install

      - name: Build static file
        working-directory: ./myPage
        run: yarn run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-northeast-2

      - name: Deploy static site to s3 bucket
        working-directory: ./myPage
        run: aws s3 sync ./dist s3://yonghoon-jeong-threejs

        #(https://youtu.be/lZ2SwKxcc88)